/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 board.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Board(props) {
  const { nodes, materials } = useGLTF('/board.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Mat_Boards} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Mat_Frames} />
      </group>
    </group>
  )
}

useGLTF.preload('/board.gltf')
