/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 infinity_loop.gltf --transform 
Files: infinity_loop.gltf [3.19KB] > C:\Users\Dell\Desktop\My_website\docs\public\infinity_loop-transformed.glb [29.09KB] (-812%)
Author: romullus (https://sketchfab.com/romullus)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/infinity-loop-c6989de854ea4acab75b7d5ed70ef901
Title: Infinity Loop
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Infinity(props) {
  const { nodes, materials } = useGLTF('/infinity_loop-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} position={[0, 1.204, -1.949]} rotation={[-Math.PI, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/infinity_loop-transformed.glb')
