/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 laptop.gltf --transform 
Files: laptop.gltf [9.52KB] > C:\Users\Dell\Desktop\My_website\docs\public\laptop-transformed.glb [94.33KB] (-891%)
Author: Uğur Yakışık (https://sketchfab.com/UgurYksk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-c1988d0aa23544c683adfe53c3cec0c0
Title: laptop
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Laptop(props) {
  const { nodes, materials } = useGLTF('/laptop-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.002']} position={[-0.929, 0, -0.308]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Material} position={[-0.929, 0, -0.308]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['Material.001']} position={[0, 0.13, 0]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Material.005']} position={[0, 1.408, -1.343]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/laptop-transformed.glb')
