/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 server_racking_system.gltf --transform 
Files: server_racking_system.gltf [695.61KB] > C:\Users\Dell\Desktop\My_website\docs\public\server_racking_system-transformed.glb [525.81KB] (24%)
Author: wpanayides (https://sketchfab.com/mcpanayides)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/server-racking-system-6fe2cacf836b4aed96c650b286db5486
Title: Server Racking System
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Server(props) {
  const { nodes, materials } = useGLTF('/server_racking_system-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box040_Black_Metal_Plate_0.geometry} material={materials.PaletteMaterial001} position={[0, 0.137, -0.027]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['Rectangle223_21_-_Default_0'].geometry} material={materials.PaletteMaterial002} position={[-0.087, 1.57, 0.526]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.Rectangle223_blue_light_0.geometry} material={materials.PaletteMaterial003} position={[-0.087, 1.57, 0.526]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/server_racking_system-transformed.glb')
